# Site Settings
name: Holiday Specials 
title: Holiday Specials
description: Check out our full list of holiday special episodes from your favorite TV shows!
tags:
  - special
  - holiday
  - episodes
  - show
show_hero: true
menu:
  - title: Home
    url: /
  - title: Contact
    url: /contact
email: mariesolo@gmail.com
# See: https://disqus.com/
disqus_username: disqus_username
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: mknadlgr
image: https://res.cloudinary.com/special-e/w_1000,ar_16:9,c_fill,g_auto,e_sharpen/Site%20assets/hero_2.png
google_analytics: G-5FTBXR7E6J


# Social Media Settings
# Remove the item if you don't need it
github_username: github_username
facebook_username: facebook_username
twitter_username: twitter_username
instagram_username: tv_specials
linkedin_username: linkedin_username
medium_username: medium_username


# Posts Settings
two_columns_layout: true


# Advanced Settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tvspecials.net/" # the base hostname & protocol for your site
google_analytics: "G-5FTBXR7E6J"
language: "en"
categories_folder: category
sent_message_url: "/contact/message-sent/"


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
use_logo: true

# SASS
sass:
  style: compressed

# Exclude my node related stuff
exclude: [
  'package.json',
  'package-lock.json',
  'src',
  'node_modules',
  'initpost.sh',
  'Gemfile',
  'Gemfile.lock',
  'gulpfile.js',
  'README.md'
]