name: Holiday Specials 
title: Holiday Specials
description: Holiday-themed episodes of your favorite TV shows
tags:
  - special
  - holiday
  - episodes
  - show
show_hero: true
menu:
  - title: Home
    url: /
  - title: Contact
    url: /contact
email: mariesolo@gmail.com
# See: https://disqus.com/
disqus_username: disqus_username
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: formspree_form_id
image: https://res.cloudinary.com/special-e/w_1000,ar_16:9,c_fill,g_auto,e_sharpen/Site%20assets/hero_2.png
